FROM nginx:latest

# Remove default nginx static files (optional but cleaner)
RUN rm -rf /usr/share/nginx/html/*

# Copy your custom index.html
COPY index.html /usr/share/nginx/html/

# Expose container port
EXPOSE 80